### ISSUE TITLE
surpyvor merge fail, but bcftools merge doesn't 

### ISSUE THREAD

**Issue by Tintest** [wdecoster/surpyvor#6] opened 2020-03-06 17:07 UTC
Hello, 

I'm having some issues with surpyvor merge. I'm trying to process .vcf from GATK4 germline CNV caller, but their format is a bit weird. I modified it a bit and added some information to this .vcf, but I still can't use surpyvor merge.

```
surpyvor -v
surpyvor: 0.6.0, SURVIVOR 1.0.6
```

```
surpyvor merge --variants NIST002A_S1_30_sorted.vcf.gz NIST002B_S2_30_sorted.vcf.gz -o toto.vcf
Executing SURVIVOR...DONE
Writing to /tmp/bcftools-sort.r176Y3
[E::vcf_parse_format] Incorrect number of FORMAT fields at 1:68821
```

I tried to use ```bcftools merge``` with the same .vcfs and it worked. Is surpyvor doing more than bcftools ? 

I also tried ```surpyvor upset``` but same thing with supplementary errors.

```
surpyvor upset --variants NIST002A_S1_30_sorted.vcf.gz NIST002B_S2_30_sorted.vcf.gz --names NIST002A_S1_30 NIST002B_S2_30 --plotout toto.png
Executing SURVIVOR...DONE
Writing to /tmp/bcftools-sort.XR28uJ
[E::vcf_parse_format] Incorrect number of FORMAT fields at 1:68821
Traceback (most recent call last):
  File "/home/tintest/miniconda3/bin/surpyvor", line 10, in <module>
    sys.exit(main())
  File "/home/tintest/miniconda3/lib/python3.7/site-packages/surpyvor/surpyvor.py", line 42, in main
    upset(args)
  File "/home/tintest/miniconda3/lib/python3.7/site-packages/surpyvor/surpyvor.py", line 123, in upset
    names=args.names or args.variants)
  File "/home/tintest/miniconda3/lib/python3.7/site-packages/surpyvor/utils.py", line 74, in make_sets
    for v in VCF(vcf):
  File "cyvcf2/cyvcf2.pyx", line 197, in cyvcf2.cyvcf2.VCF.__init__
OSError: b'/tmp/tmp0gx8h3ph' if not valid bcf or vcf
```

I tried ```bcftools sort```, it also worked.

Here is the sample .vcfs :

https://filesender.renater.fr/?s=download&token=b95e37c9-059d-5e90-01c1-0080fb412a5c

Can you help me ?

Regards

**Comment by wdecoster** [comment] 2020-03-10 11:25
> I tried to use bcftools merge with the same .vcfs and it worked. Is surpyvor doing more than bcftools ?

bcftools will merge on coordinates. As such your structural variants are required to have exacly the same breakpoints, which may be unrealistic. surpyvor allows some flexibility.
I've downloaded your files and reproduced your issue, but his is caused by how SURVIVOR handles your file, and that's not something that I can fix. I'll have to tag @fritzsedlazeck for that!

SURVIVOR makes these fields in the vcf file for your first variant (split over 3 lines for clarity):
![image](https://user-images.githubusercontent.com/11660522/76304402-a2eff100-62c3-11ea-841c-32e8d5e488c1.png)


this output was created with: 
```
SURVIVOR merge samples 500 1 1 -1 -1 50 merged_test.vcf
grep 68821  merged_test.vcf  | cut -f9-11 | tr '\t' '\n' | tr ':' '\t' | column | less
```

Cheers,
Wouter

**Comment by fritzsedlazeck** [comment] 2020-03-10 13:56
Hi Guys,
whats exactly the issue?  I merged the two vcf files resulting in the attached merged file. 
Thx
Fritz

[tmp.merge.vcf.gz](https://github.com/wdecoster/surpyvor/files/4312776/tmp.merge.vcf.gz)

**Comment by wdecoster** [comment] 2020-03-10 14:08
That looks different now from the output I posted above:
```
GT      PSV     LN      DR      ST      QV      TY      ID      RAL     AAL     CO
./.     NA      1269430 0,0     ++      .       NA      CNV_1_68821_1338251     NA      NA      1_68821-1_1338251
./.     NA      1269430 0,0     ++      .       NA      CNV_1_68821_1338251     NA      NA      1_68821-1_1338251
```
Which version of SURVIVOR did you use? GitHub HEAD? I'm on 1.0.6.

W

**Comment by Tintest** [comment] 2020-03-10 14:32
@fritzsedlazeck file seems to have been produced with SURVIVOR 1.0.7. Indeed last release seems to be 1.0.7. Maybe this issue will be solved if surpyvor  used this last release which improved merging :)

Regards.

**Comment by wdecoster** [comment] 2020-03-10 14:38
Gotcha, that's probably going to solve this issue. I'll update the conda recipe.

**Comment by Tintest** [comment] 2020-03-10 14:44
Thank you for that and thank you to both of you for your work.

Regards.

**Comment by fritzsedlazeck** [comment] 2020-03-10 16:02
Thanks guys for reaching out. 
Fritz

**Comment by wdecoster** [comment] 2020-03-11 10:37
New SURVIVOR 1.0.7 will be on Bioconda soon: https://github.com/bioconda/bioconda-recipes/pull/20802 and then this issue should be solved
(I needed some help to get the build to pass the tests...)

**Closed as completed by wdecoster** 2020-03-11 10:37 UTC
